export const RN_FILTER_PAYROLL_DATA='filterpayrolldata'
export const RN_PERIODIC_COMPNAY_TOTAL='periodiccompanytotal'
export const RN_AUTH_TAXTYPE_TOTAL='periodicauthtaxtypetotal'
//Sample Test UI Render Names
export const RN_EMPLOYEE_LIST='employeelist'
export const RN_ADD_EMPLOYEE='addemployee'
export const RN_EMPLOYEE_GRID='employeegrid'
export const RN_MONTHLY_CHART='monthlypaymentschart'
export const RN_IMPORT_UPLOAD='importupload'
export const RN_TEST_CSS='testcss'
export const RN_PERIODIC_COMP='periodiccomp'
export const RN_PERIODIC_AUTH='periodicauth'