export const RN_FILTER_PAYROLL_DATA='filterpayrolldata'
export const RN_PERIODIC_COMPNAY_TOTAL='periodiccompanytotal'
export const RN_AUTH_TAXTYPE_TOTAL='periodicauthtaxtypetotal'
export const RN_LIABILITIES_CHART='liabilitieschart'
export const RN_VARIANCE_CHART='variancechart'